export const EXTEND = {
  demo: false,
  subtitle: [],
  option: {
    name: '',
    videoType: 1,
    subtitleType: 1,
    subtitleMode: 1,
    burnPreset: 'fast',
    burnSize: 0,
    translateTo: '',
  },
  style: {
    Name: 'Default',
    Fontname: 'Source Han Sans CN Normal',
    Fontsize: 20,
    PrimaryColour: '&H00FFFFFF',
    SecondaryColour: '&H00FFFFFF',
    OutlineColour: '&H00000000',
    SecondaryOutlineColour: '&H00000000',
    BackColour: '&H00000000',
    Bold: 0,
    Italic: 0,
    Underline: 0,
    StrikeOut: 0,
    ScaleX: 100,
    ScaleY: 100,
    Spacing: 0,
    Angle: 0,
    BorderStyle: 1,
    Outline: 1,
    Shadow: 1,
    Alignment: 2,
    MarginL: 10,
    MarginR: 10,
    MarginV: 10,
    Encoding: 134,
  },
  offline: {
    canPlay: false,
    subtitleFile: null,
    audioFile: null,
    audioBlobUrl: null,
    videoFile: null,
    videoBlobUrl: '',
    videoPoster: '',
    videoDuration: 0,
    videoHasAudio: true,
    videoHasVideo: true,
    thumbnail: {
      url: '',
      height: 0,
      width: 0,
      number: 0,
      column: 0,
    },
  },
};
